### ISSUE TITLE
I want to show lists of select in first screen

### ISSUE THREAD

**Issue by magic990619** [sharathchandramg/react-native-formo#111]
I recently had a chance to look at this react-native-form0.
It is really nice.
But you show choices list of 'select' type on the second screen.
Is there any option to show it on the first screen?

**Comment by prtkkmrsngh** [comment]
@magic990619 Please try picker field, it will show choices like a dropdown menu.

**Comment by magic990619** [comment]
Thanks.
But I think it can't show multiple choices list.
And I don't want dropdown menu. 
I want to show multiple checkboxes list.
Like this.
![2020-02-13_5-16-41](https://user-images.githubusercontent.com/46446076/74439076-5f1ede80-4e20-11ea-8f80-b7d7c1f66f7b.png)
![2020-02-13_5-19-20](https://user-images.githubusercontent.com/46446076/74439196-a0af8980-4e20-11ea-84e2-05f728986d58.png)
I like this multiple checkboxes list. But I want to show it on the first screen.
Any way?

**Comment by prtkkmrsngh** [comment]
@magic990619 No, this package doesn't have this capability.
